id: I76668A96
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:44:54+00:00'
last_modified: '2022-06-07T15:19:41.235380+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3994
  title: རིན་ཆེན་དངུལ་ཆུ་སྦྱར་སྡེ་ཕྱོགས་བསྡེབས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    7F7D:
      image_group_id: I1KG4060
      title: ''
      total_pages: 446
      order: 1
      base_file: 7F7D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
