id: P001835
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG3994
  title: རིན་ཆེན་དངུལ་ཆུ་སྦྱར་སྡེ་ཕྱོགས་བསྡེབས་
  author: ''
  volumes:
    7c7edbb65a2e4fdd816b8d2697c16b90:
      image_group_id: I1KG4060
      title: ''
      volume_number: 1
      total_pages: 446
      base_file: v001.txt
